Update workflow

diff --git a/.github/workflows/01-building-blocks.yml b/.github/workflows/01-building-blocks.yml
--- a/.github/workflows/01-building-blocks.yml
+++ b/.github/workflows/01-building-blocks.yml
@@ -11,11 +11,10 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
-      - name: Failed step
+      - name: Fail step
         run: |
-            echo: "I will fail"
-            exit 1 
-      - name: Say goodbye step
-        run: |
-            echo: "Goodbye"
+          echo "I will fail"
+          exit 1
+      - name: Say goodbye
+        run: echo "Goodbye!"
         
